src/jp/co/sekainet/cms/entity/User.java
package jp.co.sekainet.cms.entity;

import java.io.Serializable;

public class User implements Serializable {

    /** serialVersionUID. */
    private static final long serialVersionUID = 8723380662139643299L;

    private long id;

    private String loginId;

    private String password;

    private String name;

    private String phonetic;

    private String postalCode;

    private int prefectureId;

    private String city;

    private String address;

    private String telephone;

    private String email;

    private String note;

    private boolean admin;

    private static final String[] PREFECTURES = new String[] {
            "未設定",
            "北海道",
            "青森県",
            "岩手県",
            "宮城県",
            "秋田県",
            "山形県",
            "福島県",
            "茨城県",
            "栃木県",
            "群馬県",
            "埼玉県",
            "千葉県",
            "東京都",
            "神奈川県",
            "新潟県",
            "富山県",
            "石川県",
            "福井県",
            "山梨県",
            "長野県",
            "岐阜県",
            "静岡県",
            "愛知県",
            "三重県",
            "滋賀県",
            "京都府",
            "大阪府",
            "兵庫県",
            "奈良県",
            "和歌山県",
            "鳥取県",
            "島根県",
            "岡山県",
            "広島県",
            "山口県",
            "徳島県",
            "香川県",
            "愛媛県",
            "高知県",
            "福岡県",
            "佐賀県",
            "長崎県",
            "熊本県",
            "大分県",
            "宮崎県",
            "鹿児島県",
            "沖縄県",
    };

    public String getPrefecture() {
        if (prefectureId > 0 && prefectureId < PREFECTURES.length) {
            return PREFECTURES[prefectureId];
        }
        return PREFECTURES[0];
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getLoginId() {
        return loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhonetic() {
        return phonetic;
    }

    public void setPhonetic(String phonetic) {
        this.phonetic = phonetic;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public int getPrefectureId() {
        return prefectureId;
    }

    public void setPrefectureId(int prefectureId) {
        this.prefectureId = prefectureId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public boolean isAdmin() {
        return admin;
    }

    public void setAdmin(boolean admin) {
        this.admin = admin;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", loginId=" + loginId + ", password=" + password +
                ", name=" + name + ", phonetic=" + phonetic + ", postalCode=" + postalCode +
                ", prefectureId=" + prefectureId + ", city=" + city + ", address=" + address +
                ", telephone=" + telephone + ", email=" + email + ", note=" + note +
                ", admin=" + admin + "]";
    }
}

src/jp/co/sekainet/cms/servlet/ContentsServlet.java
package jp.co.sekainet.cms.servlet;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/contents")
public class ContentsServlet extends HttpServlet {

    /** serialVersionUID. */
    private static final long serialVersionUID = -5042424037263982657L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("contents.jsp");
        requestDispatcher.forward(request, response);
    }
}

src/jp/co/sekainet/cms/servlet/LoginServlet.java
package jp.co.sekainet.cms.servlet;

import java.io.IOException;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jp.co.sekainet.cms.dao.UserDAO;
import jp.co.sekainet.cms.entity.User;

@WebServlet("/login")
public class LoginServlet extends HttpServlet {

    /** serialVersionUID. */
    private static final long serialVersionUID = -2736003243179290000L;

    private UserDAO userDao = new UserDAO();

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("login.jsp");
        requestDispatcher.forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String loginId = request.getParameter("loginId");
        String password = request.getParameter("password");
        User loginUser = userDao.findByLoginId(loginId);
        if (loginUser != null && loginUser.getPassword().equals(password)) {
            request.getSession().setAttribute("loginUser", loginUser);
            if (loginUser.isAdmin()) {
                response.sendRedirect(request.getContextPath() + "/user/list");
            } else {
                response.sendRedirect(request.getContextPath() + "/contents");
            }
            return;
        }
        request.setAttribute("message", "ログインに失敗しました。");
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("login.jsp");
        requestDispatcher.forward(request, response);
    }
}

src/jp/co/sekainet/cms/servlet/UserEditServlet.java
package jp.co.sekainet.cms.servlet;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jp.co.sekainet.cms.dao.UserDAO;
import jp.co.sekainet.cms.entity.User;

@WebServlet("/user/edit")
public class UserEditServlet extends HttpServlet {

    /** serialVersionUID. */
    private static final long serialVersionUID = 4335048583325569642L;

    private UserDAO userDao = new UserDAO();

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        // 管理者としてログインしていない場合はログインページへ遷移.
        User loginUser = (User)request.getSession().getAttribute("loginUser");
        if (loginUser == null || !loginUser.isAdmin()) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }
        User user = null;
        if (request.getParameter("id") != null) {
            try {
                int id = Integer.parseInt(request.getParameter("id"));
                user = userDao.findById(id);
            } catch (Exception ignore) {}
            if (user == null) {
                // 未入力か数値を指定されなかった場合はID指定なしとしてリダイレクトする.
                response.sendRedirect(request.getRequestURI());
                return;
            }
        } else {
            user = new User();
        }
        request.setAttribute("user", user);
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("/user_edit.jsp");
        requestDispatcher.forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        User user = null;
        // バリデーション処理
        Map<String, String> validationMessages = new HashMap<>();
        // IDが指定されている場合は更新、されていない場合は追加
        if (request.getParameter("id") != null && !request.getParameter("id").isEmpty()) {
            try {
                long userId = Long.parseLong(request.getParameter("id"));
                user = userDao.findById(userId);
                if (user == null) {
                    validationMessages.put("id", "指定されたIDのユーザーは存在しないため更新できません。");
                }
            } catch(NumberFormatException e) {
                validationMessages.put("id", "IDは数値を入力して下さい。");
            }
        } else {
            user = new User();
        }
        if (request.getParameter("loginId") == null || request.getParameter("loginId").isEmpty()) {
            validationMessages.put("loginId", "ログインIDは必須です");
        } else if (request.getParameter("loginId").length() < 6) {
            validationMessages.put("loginId", "ログインIDは6文字以上で入力して下さい");
        } else if (request.getParameter("loginId").length() > 50) {
            validationMessages.put("loginId", "ログインIDは50文字以下で入力して下さい");
        }
        if (request.getParameter("password") == null || request.getParameter("password").isEmpty()) {
            validationMessages.put("password", "パスワードは必須です");
        } else if (request.getParameter("password").length() < 8) {
            validationMessages.put("password", "パスワードは8文字以上で入力して下さい");
        } else if (request.getParameter("password").length() > 100) {
            validationMessages.put("password", "パスワードは100文字以下で入力して下さい");
        }
        if (request.getParameter("name") == null || request.getParameter("name").isEmpty()) {
            validationMessages.put("name", "名前は必須です");
        } else if (request.getParameter("name").length() > 50) {
            validationMessages.put("name", "名前は50文字以下で入力して下さい");
        }
        if (request.getParameter("phonetic") != null && request.getParameter("phonetic").length() > 100) {
            validationMessages.put("phonetic", "よみがなは100文字以下で入力して下さい");
        } else if (request.getParameter("phonetic") != null &&
                !request.getParameter("phonetic").isEmpty() &&
                !request.getParameter("phonetic").matches("^[ぁ-ゞー]+$")) {
            validationMessages.put("phonetic", "よみがなはすべて平仮名で入力して下さい");
        }
        if (request.getParameter("postalCode") != null &&
                !request.getParameter("postalCode").isEmpty() &&
                !request.getParameter("postalCode").matches("\\d{3}-\\d{4}")) {
            validationMessages.put("postalCode", "郵便番号はハイフンを含めて7桁の数値で入力して下さい");
        }
        if (request.getParameter("prefectureId") != null && !request.getParameter("prefectureId").isEmpty()) {
            try {
                int prefectureId = Integer.parseInt(request.getParameter("prefectureId"));
                if (prefectureId < 0 || prefectureId > 47) {
                    validationMessages.put("prefectureId", "都道府県の選択値が不正です。");
                }
            } catch(NumberFormatException e) {
                validationMessages.put("prefectureId", "都道府県の選択値が不正です。");
            }
        }
        if (request.getParameter("city") != null &&
                request.getParameter("city").length() > 50) {
            validationMessages.put("city", "市区町村は50文字以下で入力して下さい");
        }
        if (request.getParameter("address") != null &&
                request.getParameter("address").length() > 50) {
            validationMessages.put("address", "住所は50文字以下で入力して下さい");
        }
        if (request.getParameter("telephone") != null &&
                !request.getParameter("telephone").isEmpty() &&
                !request.getParameter("telephone").matches("0\\d{1,4}-\\d{1,4}-\\d{3,4}")) {
            validationMessages.put("telephone", "電話番号ははハイフンを含めて数値で入力して下さい");
        }
        if (request.getParameter("email") != null &&
                !request.getParameter("email").isEmpty() &&
                !request.getParameter("email").matches("[^@]+@.+\\..+")) {
            validationMessages.put("email", "メールアドレスの入力値が不正です");
        }
        if (request.getParameter("note") != null && request.getParameter("note").length() > 500) {
            validationMessages.put("note", "備考は500文字以下で入力して下さい");
        }
        // パラメータをuserへ詰替
        user.setLoginId(request.getParameter("loginId"));
        user.setPassword(request.getParameter("password"));
        user.setName(request.getParameter("name"));
        user.setPhonetic(request.getParameter("phonetic"));
        user.setPostalCode(request.getParameter("postalCode"));
        if (request.getParameter("prefectureId") != null &&
                !request.getParameter("prefectureId").isEmpty()) {
            user.setPrefectureId(Integer.parseInt(request.getParameter("prefectureId")));
        }
        user.setCity(request.getParameter("city"));
        user.setAddress(request.getParameter("address"));
        user.setTelephone(request.getParameter("telephone"));
        user.setEmail(request.getParameter("email"));
        user.setNote(request.getParameter("note"));
        try {
            user.setAdmin(Boolean.parseBoolean(request.getParameter("admin")));
        } catch (Exception ignore) {}
        // バリデーションエラーがある場合は中断して画面に通知
        if (!validationMessages.isEmpty()) {
            request.setAttribute("user", user);
            request.setAttribute("message", validationMessages);
            RequestDispatcher requestDispatcher = request.getRequestDispatcher("/user_edit.jsp");
            requestDispatcher.forward(request, response);
            return;
        }
        // 挿入もしくは更新
        if (user.getId() < 1L) {
            userDao.insert(user);
        } else {
            userDao.update(user);
        }
        System.out.println(user);
        // 更新後に一覧ページを表示
        response.sendRedirect(request.getContextPath() + "/user/list");
    }

    protected User getSpecifiedUser(HttpServletRequest request) {
        try {
            int id = Integer.parseInt(request.getParameter("id"));
            return userDao.findById(id);
        } catch (Exception ignore) {
            // 未入力か数値を指定されなかった場合は何もせずnullを返す.
        }
        return null;
    }

}

src/jp/co/sekainet/cms/servlet/UserListServlet.java
package jp.co.sekainet.cms.servlet;

import java.io.IOException;
import java.util.List;

import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import jp.co.sekainet.cms.dao.UserDAO;
import jp.co.sekainet.cms.entity.User;

@WebServlet("/user/list")
public class UserListServlet extends HttpServlet {

    /** serialVersionUID. */
    private static final long serialVersionUID = -3400232553501413955L;

    private UserDAO userDao = new UserDAO();

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        // 管理者としてログインしていない場合はログインページへ遷移.
        User loginUser = (User)request.getSession().getAttribute("loginUser");
        if (loginUser == null || !loginUser.isAdmin()) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }
        List<User> users = userDao.findAll();
        request.setAttribute("users", users);
        RequestDispatcher requestDispatcher = request.getRequestDispatcher("/user_list.jsp");
        requestDispatcher.forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
    }

}

WebContent/contents.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>顧客管理システム:コンテンツ</title>
<style type="text/css">
span.error { color: red; }
</style>
</head>
<body>
  <p>${loginUser.name}さん <a href="./logout">ログアウト</a></p>
  <p>コンテンツがここに表示される。</p>
</body>
</html>

WebContent/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>顧客管理システム:ログイン</title>
<style type="text/css">
span.error { color: red; }
</style>
</head>
<body>
  <form action="./login" method="post">
    <p>顧客管理システムへようこそ<p>
    <p>ログインID: <input name="loginId" type="text"></p>
    <p>パスワード: <input name="password" type="password"></p>
    <p><span class="error">${message}</span></p>
    <p><input type="submit" value="送信"></p>
  </form>
</body>
</html>

WebContent/user_edit.jsp
<%@ page import="jp.co.sekainet.cms.entity.User"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>顧客管理システム:ユーザー編集</title>
<style type="text/css">
span.error { color: red; }
</style>
</head>
<body>
  <p>${loginUser.name}さん <a href="../logout">ログアウト</a></p>
  ユーザーの登録
  <form action="./edit${user.id == 0 ? '' : '?id='.concat(user.id)}" method="post">
    <p>ID: <input name="id" type="text" readonly value="${user.id == 0 ? '' : user.id}">
      <span class="error">${message.id}</span>
    </p>
    <p>ログインID: <input name="loginId" type="text" value="${user.loginId}">
      <span class="error">${message.loginId}</span>
    </p>
    <p>パスワード: <input name="password" type="password" value="${user.password}">
      <span class="error">${message.password}</span>
    </p>
    <p>名称: <input name="name" type="text" value="${user.name}">
      <span class="error">${message.name}</span>
    </p>
    <p>よみがな: <input name="phonetic" type="text" value="${user.phonetic }">
      <span class="error">${message.phonetic}</span>
    </p>
    <p>郵便番号: <input name="postalCode" type="text" value="${user.postalCode}">
      <span class="error">${message.postalCode}</span>
    </p>
    <p>都道府県: <select name="prefectureId" >
      <optgroup label="未選択">
        <option value="0" label="未選択" ${user.prefectureId == 0 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="北海道・東北">
        <option value="1" label="北海道" ${user.prefectureId == 1 ? 'selected' : ''}>
        <option value="2" label="青森県" ${user.prefectureId == 2 ? 'selected' : ''}>
        <option value="3" label="岩手県" ${user.prefectureId == 3 ? 'selected' : ''}>
        <option value="4" label="宮城県" ${user.prefectureId == 4 ? 'selected' : ''}>
        <option value="5" label="秋田県" ${user.prefectureId == 5 ? 'selected' : ''}>
        <option value="6" label="山形県" ${user.prefectureId == 6 ? 'selected' : ''}>
        <option value="7" label="福島県" ${user.prefectureId == 7 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="関東">
        <option value="8" label="茨城県" ${user.prefectureId == 8 ? 'selected' : ''}>
        <option value="9" label="栃木県" ${user.prefectureId == 9 ? 'selected' : ''}>
        <option value="10" label="群馬県" ${user.prefectureId == 10 ? 'selected' : ''}>
        <option value="11" label="埼玉県" ${user.prefectureId == 11 ? 'selected' : ''}>
        <option value="12" label="千葉県" ${user.prefectureId == 12 ? 'selected' : ''}>
        <option value="13" label="東京都" ${user.prefectureId == 13 ? 'selected' : ''}>
        <option value="14" label="神奈川県" ${user.prefectureId == 14 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="中部">
        <option value="15" label="新潟県" ${user.prefectureId == 15 ? 'selected' : ''}>
        <option value="16" label="富山県" ${user.prefectureId == 16 ? 'selected' : ''}>
        <option value="17" label="石川県" ${user.prefectureId == 17 ? 'selected' : ''}>
        <option value="18" label="福井県" ${user.prefectureId == 18 ? 'selected' : ''}>
        <option value="19" label="山梨県" ${user.prefectureId == 19 ? 'selected' : ''}>
        <option value="20" label="長野県" ${user.prefectureId == 20 ? 'selected' : ''}>
        <option value="21" label="岐阜県" ${user.prefectureId == 21 ? 'selected' : ''}>
        <option value="22" label="静岡県" ${user.prefectureId == 22 ? 'selected' : ''}>
        <option value="23" label="愛知県" ${user.prefectureId == 23 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="関西">
        <option value="24" label="三重県" ${user.prefectureId == 24 ? 'selected' : ''}>
        <option value="25" label="滋賀県" ${user.prefectureId == 25 ? 'selected' : ''}>
        <option value="26" label="京都府" ${user.prefectureId == 26 ? 'selected' : ''}>
        <option value="27" label="大阪府" ${user.prefectureId == 27 ? 'selected' : ''}>
        <option value="28" label="兵庫県" ${user.prefectureId == 28 ? 'selected' : ''}>
        <option value="29" label="奈良県" ${user.prefectureId == 29 ? 'selected' : ''}>
        <option value="30" label="和歌山県" ${user.prefectureId == 30 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="中国">
        <option value="31" label="鳥取県" ${user.prefectureId == 31 ? 'selected' : ''}>
        <option value="32" label="島根県" ${user.prefectureId == 32 ? 'selected' : ''}>
        <option value="33" label="岡山県" ${user.prefectureId == 33 ? 'selected' : ''}>
        <option value="34" label="広島県" ${user.prefectureId == 34 ? 'selected' : ''}>
        <option value="35" label="山口県" ${user.prefectureId == 35 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="四国">
        <option value="36" label="徳島県" ${user.prefectureId == 36 ? 'selected' : ''}>
        <option value="37" label="香川県" ${user.prefectureId == 37 ? 'selected' : ''}>
        <option value="38" label="愛媛県" ${user.prefectureId == 38 ? 'selected' : ''}>
        <option value="39" label="高知県" ${user.prefectureId == 39 ? 'selected' : ''}>
      </optgroup>
      <optgroup label="九州・沖縄">
        <option value="40" label="福岡県" ${user.prefectureId == 40 ? 'selected' : ''}>
        <option value="41" label="佐賀県" ${user.prefectureId == 41 ? 'selected' : ''}>
        <option value="42" label="長崎県" ${user.prefectureId == 42 ? 'selected' : ''}>
        <option value="43" label="熊本県" ${user.prefectureId == 43 ? 'selected' : ''}>
        <option value="44" label="大分県" ${user.prefectureId == 44 ? 'selected' : ''}>
        <option value="45" label="宮崎県" ${user.prefectureId == 45 ? 'selected' : ''}>
        <option value="46" label="鹿児島県" ${user.prefectureId == 46 ? 'selected' : ''}>
        <option value="47" label="沖縄県" ${user.prefectureId == 47 ? 'selected' : ''}>
      </optgroup>
    </select>
      <span class="error">${message.prefectureId}</span>
    </p>
    <p>市区町村: <input name="city" type="text" value="${user.city}">
      <span class="error">${message.city}</span>
    </p>
    <p>番地・建物: <input name="address" type="text" value="${user.address}">
      <span class="error">${message.address}</span>
    </p>
    <p>電話番号: <input name="telephone" type="tel" value="${user.telephone}">
      <span class="error">${message.telephone}</span>
    </p>
    <p>メールアドレス: <input name="email" type="email" value="${user.email}">
      <span class="error">${message.email}</span>
    </p>
    <p>備考: <textarea name="note" rows=”10″ cols=”60″>${user.note}</textarea>
      <span class="error">${message.note}</span>
    </p>
    <p>管理者: <input name="admin" type="checkbox" ${user.admin ? 'checked' : ''} value="true">
      <span class="error">${message.admin}</span>
    </p>
    <p>
      <input type="submit" value="送信">
      <a href="./list">一覧へ戻る</a>
    </p>
  </form>
</body>
</html>

WebContent/user_list.jsp
<%@ page import="jp.co.sekainet.cms.entity.User"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>顧客管理システム:ユーザー一覧</title>
<style type="text/css">
span.error { color: red; }
</style>
</head>
<body>
  <p>${loginUser.name}さん <a href="../logout">ログアウト</a></p>
  <a href="./edit">新規作成</a>
  <table border="1">
    <tr>
      <th>ID</th>
      <th>ログインID</th>
      <th>名前</th>
      <th>よみがな</th>
      <th>郵便番号</th>
      <th>都道府県</th>
      <th>市区町村</th>
      <th>番地・建物</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>備考</th>
      <th>管理者</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
    <c:forEach var="user" items="${users}" varStatus="s">
    <tr>
      <td>${user.id}</td>
      <td>${user.loginId}</td>
      <td>${user.name}</td>
      <td>${user.phonetic}</td>
      <td>${user.postalCode}</td>
      <td>${user.prefecture}</td>
      <td>${user.city}</td>
      <td>${user.address}</td>
      <td>${user.telephone}</td>
      <td>${user.email}</td>
      <td>${user.note}</td>
      <td><input type="checkbox" ${user.admin ? 'checked' : ''} onclick="return false;"></td>
      <td><a href="./edit?id=${user.id}">編集</a></td>
      <td><a href="./delete?id=${user.id}"
            onclick="return window.confirm('「${user.name}」を削除します。よろしいですか？');">削除</a></td>
    </tr>
    </c:forEach>
  </table>
</body>
</html>